version: '3.9'
services:
  db:
    image: mysql:8.3
    container_name: brnd_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # match .env
      MYSQL_DATABASE: brnd_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
